In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('housing_data_CDMX.csv')

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 18234 entries, 0 to 18233
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   property_type               18234 non-null  str
 1   places                      18234 non-null  str
 2   lat-lon                     18234 non-null  str
 3   price                       18234 non-null  float64
 4   currency                    18234 non-null  str
 5   price_aprox_local_currency  18234 non-null  float64
 6   price_aprox_usd             18234 non-null  float64
 7   surface_total_in_m2         18234 non-null  float64
 8   surface_covered_in_m2       18234 non-null  float64
 9   price_usd_per_m2            18234 non-null  float64
 10  price_per_m2                18234 non-null  float64
dtypes: float64(7), str(4)
memory usage: 1.5 MB

In [4]:
df.head()

,property_type,places,lat-lon,price,currency,price_aprox_local_currency,price_aprox_usd,surface_total_in_m2,surface_covered_in_m2,price_usd_per_m2,price_per_m2
0,apartment,MiguelHidalgo,"23.634501,-102.552788",5500000.0,MXN,5450245.50,289775.66,54.0,54.0,5366.215926,101851.85190
1,house,Iztapalapa,"19.31033,-99.068557",1512000.0,MXN,1498321.97,79661.96,80.0,80.0,995.774500,18900.00000
2,apartment,Tlalpan,"19.279771,-99.234597",926667.0,MXN,918284.00,48822.82,100.0,100.0,488.228200,9266.67000
3,apartment,MiguelHidalgo,"23.634501,-102.552788",6410000.0,MXN,6352013.39,337720.36,135.0,135.0,2501.632296,47481.48148
4,apartment,MiguelHidalgo,"19.432657,-99.177444",4416000.0,MXN,4376051.62,232663.51,87.0,87.0,2674.293218,50758.62069

# Duplicated and nulls handling

In [5]:
df.duplicated().sum()

np.int64(2953)

In [6]:
df.drop_duplicates(inplace=True)

In [7]:
df.isnull().sum()

property_type                 0
places                        0
lat-lon                       0
price                         0
currency                      0
price_aprox_local_currency    0
price_aprox_usd               0
surface_total_in_m2           0
surface_covered_in_m2         0
price_usd_per_m2              0
price_per_m2                  0
dtype: int64

# split lat-lon column to two column

In [8]:
df[['latitude', 'longitude']] = df['lat-lon'].str.split(',', expand=True)

df['latitude'] = pd.to_numeric(df['latitude'], errors='coerce')
df['longitude'] = pd.to_numeric(df['longitude'], errors='coerce')

df.drop('lat-lon', axis=1, inplace=True)

Chack nulls for new columns

In [9]:
df.isnull().sum()

property_type                   0
places                          0
price                           0
currency                        0
price_aprox_local_currency      0
price_aprox_usd                 0
surface_total_in_m2             0
surface_covered_in_m2           0
price_usd_per_m2                0
price_per_m2                    0
latitude                      103
longitude                     103
dtype: int64

In [10]:
df[['latitude', 'longitude']] = df[['latitude', 'longitude']].fillna(df[['latitude', 'longitude']].mean())

In [11]:
df.head()

,property_type,places,price,currency,price_aprox_local_currency,price_aprox_usd,surface_total_in_m2,surface_covered_in_m2,price_usd_per_m2,price_per_m2,latitude,longitude
0,apartment,MiguelHidalgo,5500000.0,MXN,5450245.50,289775.66,54.0,54.0,5366.215926,101851.85190,23.634501,-102.552788
1,house,Iztapalapa,1512000.0,MXN,1498321.97,79661.96,80.0,80.0,995.774500,18900.00000,19.310330,-99.068557
2,apartment,Tlalpan,926667.0,MXN,918284.00,48822.82,100.0,100.0,488.228200,9266.67000,19.279771,-99.234597
3,apartment,MiguelHidalgo,6410000.0,MXN,6352013.39,337720.36,135.0,135.0,2501.632296,47481.48148,23.634501,-102.552788
4,apartment,MiguelHidalgo,4416000.0,MXN,4376051.62,232663.51,87.0,87.0,2674.293218,50758.62069,19.432657,-99.177444

# outliers handling

In [12]:
num_cols = df.select_dtypes(include=['number']).columns

print("Numerical columns:", num_cols)

df[num_cols].describe()

Numerical columns: Index(['price', 'price_aprox_local_currency', 'price_aprox_usd',
       'surface_total_in_m2', 'surface_covered_in_m2', 'price_usd_per_m2',
       'price_per_m2', 'latitude', 'longitude'],
      dtype='str')

,price,price_aprox_local_currency,price_aprox_usd,surface_total_in_m2,surface_covered_in_m2,price_usd_per_m2,price_per_m2,latitude,longitude
count,1.528100e+04,1.528100e+04,1.528100e+04,1.528100e+04,1.528100e+04,15281.000000,1.528100e+04,15281.000000,15281.000000
mean,3.751468e+06,5.481206e+06,2.914218e+05,4.825551e+03,4.798662e+03,1506.476035,2.428909e+04,19.440262,-99.206676
std,5.874121e+06,1.027769e+07,5.464384e+05,5.322727e+05,5.322714e+05,2282.316144,4.359358e+04,0.508879,0.397080
min,7.000000e+03,1.090306e+05,5.796880e+03,1.000000e+00,1.000000e+00,0.000600,1.137677e-02,19.185852,-102.552788
25%,1.029394e+06,1.090049e+06,5.795513e+04,7.000000e+01,7.000000e+01,658.581000,1.108925e+04,19.350214,-99.196831
50%,2.000000e+06,2.298022e+06,1.221799e+05,1.000000e+02,1.000000e+02,1063.816600,1.771429e+04,19.387960,-99.164986
75%,4.110000e+06,4.954768e+06,2.634324e+05,2.050000e+02,2.180000e+02,1895.811111,3.194444e+04,19.426948,-99.135841
max,2.337267e+08,3.364841e+08,1.789000e+07,6.574800e+07,6.574800e+07,175917.685571,3.338953e+06,41.577487,-90.488467

In [13]:
num_cols = [
    'price',
    'price_aprox_local_currency',
    'price_aprox_usd',
    'surface_total_in_m2',
    'surface_covered_in_m2',
    'price_usd_per_m2',
    'price_per_m2'
]

for col in num_cols:
    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)
    iqr = q3 - q1

    lower = max(0, q1 - 1.5 * iqr)
    upper = q3 + 1.5 * iqr

    outliers = ((df[col] < lower) | (df[col] > upper)).sum()

    df[col] = df[col].clip(lower=lower, upper=upper)

    print(f"{col}: {outliers} outliers clipped")

price: 1392 outliers clipped
price_aprox_local_currency: 1944 outliers clipped
price_aprox_usd: 1944 outliers clipped
surface_total_in_m2: 1407 outliers clipped
surface_covered_in_m2: 1291 outliers clipped
price_usd_per_m2: 809 outliers clipped
price_per_m2: 506 outliers clipped

In [14]:
df[num_cols] = df[num_cols].round(1)

In [15]:
df.describe()

,price,price_aprox_local_currency,price_aprox_usd,surface_total_in_m2,surface_covered_in_m2,price_usd_per_m2,price_per_m2,latitude,longitude
count,1.528100e+04,1.528100e+04,15281.000000,15281.000000,15281.000000,15281.000000,15281.000000,15281.000000,15281.000000
mean,2.987111e+06,3.680826e+06,195700.158144,152.726687,157.764152,1384.718304,22680.502899,19.440262,-99.206676
std,2.545165e+06,3.391170e+06,180299.845842,114.797614,122.576736,948.703773,15570.959255,0.508879,0.397080
min,7.000000e+03,1.090306e+05,5796.900000,1.000000,1.000000,0.000000,0.000000,19.185852,-102.552788
25%,1.029394e+06,1.090049e+06,57955.100000,70.000000,70.000000,658.600000,11089.300000,19.350214,-99.196831
50%,2.000000e+06,2.298022e+06,122180.000000,100.000000,100.000000,1063.800000,17714.300000,19.387960,-99.164986
75%,4.110000e+06,4.954768e+06,263432.400000,205.000000,218.000000,1895.800000,31944.400000,19.426948,-99.135841
max,8.730909e+06,1.075185e+07,571648.300000,407.500000,440.000000,3751.700000,63227.200000,41.577487,-90.488467

In [16]:
(df[num_cols] < 10).sum()

price                          0
price_aprox_local_currency     0
price_aprox_usd                0
surface_total_in_m2            6
surface_covered_in_m2         10
price_usd_per_m2              16
price_per_m2                   5
dtype: int64

In [17]:
for col in num_cols:
    df[col] = df[col].clip(lower=10)

In [18]:
df.describe()

,price,price_aprox_local_currency,price_aprox_usd,surface_total_in_m2,surface_covered_in_m2,price_usd_per_m2,price_per_m2,latitude,longitude
count,1.528100e+04,1.528100e+04,15281.000000,15281.000000,15281.000000,15281.000000,15281.000000,15281.000000,15281.000000
mean,2.987111e+06,3.680826e+06,195700.158144,152.729239,157.768471,1384.725286,22680.505490,19.440262,-99.206676
std,2.545165e+06,3.391170e+06,180299.845842,114.794359,122.571395,948.693624,15570.955481,0.508879,0.397080
min,7.000000e+03,1.090306e+05,5796.900000,10.000000,10.000000,10.000000,10.000000,19.185852,-102.552788
25%,1.029394e+06,1.090049e+06,57955.100000,70.000000,70.000000,658.600000,11089.300000,19.350214,-99.196831
50%,2.000000e+06,2.298022e+06,122180.000000,100.000000,100.000000,1063.800000,17714.300000,19.387960,-99.164986
75%,4.110000e+06,4.954768e+06,263432.400000,205.000000,218.000000,1895.800000,31944.400000,19.426948,-99.135841
max,8.730909e+06,1.075185e+07,571648.300000,407.500000,440.000000,3751.700000,63227.200000,41.577487,-90.488467

In [19]:
df

,property_type,places,price,currency,price_aprox_local_currency,price_aprox_usd,surface_total_in_m2,surface_covered_in_m2,price_usd_per_m2,price_per_m2,latitude,longitude
0,apartment,MiguelHidalgo,5500000.0,MXN,5450245.5,289775.7,54.0,54.0,3751.7,63227.2,23.634501,-102.552788
1,house,Iztapalapa,1512000.0,MXN,1498322.0,79662.0,80.0,80.0,995.8,18900.0,19.310330,-99.068557
2,apartment,Tlalpan,926667.0,MXN,918284.0,48822.8,100.0,100.0,488.2,9266.7,19.279771,-99.234597
3,apartment,MiguelHidalgo,6410000.0,MXN,6352013.4,337720.4,135.0,135.0,2501.6,47481.5,23.634501,-102.552788
4,apartment,MiguelHidalgo,4416000.0,MXN,4376051.6,232663.5,87.0,87.0,2674.3,50758.6,19.432657,-99.177444
...,...,...,...,...,...,...,...,...,...,...,...,...
18229,apartment,Coyoacan,4154400.0,MXN,4116818.0,218880.7,157.0,157.0,1394.1,26461.1,19.336994,-99.162355
18230,house,AlvaroObregon,706448.0,MXN,700223.2,37229.1,105.0,105.0,354.6,6728.1,19.342911,-99.224472
18231,apartment,Cuauhtemoc,621880.0,MXN,616254.3,32764.7,130.0,130.0,252.0,4783.7,19.408758,-99.129474
18232,house,MiguelHidalgo,8730909.0,MXN,10751847.6,571648.3,316.0,350.0,2168.0,37142.9,19.401079,-99.248070
18233,apartment,Cuauhtemoc,6500000.0,MXN,6442726.6,342543.4,120.0,120.0,2854.5,54166.7,19.441646,-99.151884

In [20]:
df.to_csv('housing_data_CDMX_cleaned.csv', index=False)